[[redirects]]
from = "/"
<<<<<<< HEAD
to = "/index_04_ui_copy_updated.html"
=======
<<<<<<< HEAD
to = "/index_04_ui_copy_updated.html"
=======
to = "/index_05_ui_mobileweb_ux_updated.html"
>>>>>>> develop
>>>>>>> release
status = 200
